# Generated by Django 2.0.3 on 2018-03-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180322_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notifications_type',
            new_name='Notification_type',
        ),
    ]
